version: 2.1
orbs:
  cypress: cypress-io/cypress@2.1.0
executors:
  image:
    docker:
      - image: 'cypress/base:18.6.0'
workflows:
  test:
    jobs:
      - cypress/run:
          executor: image
          yarn: true
          command: yarn build && yarn test:e2e:ci
